version: "3.1"
services:
  nginx:
    image: nginx:latest
    container_name: nginx_php
    command: nginx -g "daemon off;"
    volumes:
      - ../app:/var/www/html/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/html/
    links:
      - php
    ports:
      - "80:80"

  php:
    container_name: php_fpm
    build: php
    command: php-fpm
    volumes:
      - ../app:/var/www/html/
    ports:
      - "9000:9000"

  workspace:
    build: workspace
    container_name: workspace_php
    restart: always
    tty: true
    volumes:
      - ../app:/app
    working_dir: /app
  mysql:
    container_name: user_db
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./../db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: user
      MYSQL_USER: laravel
      MYSQL_PASSWORD: user_123
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: laravel_root
